# config/packages/vich_uploader.yaml
# vich_uploader:
#     db_driver: orm # Si vous utilisez Doctrine ORM
#     mappings:
#         media:
#             uri_prefix: /public/assets/img/media # Chemin où seront stockés les fichiers
#             upload_destination: '%kernel.project_dir%/public/assets/img/media' # Emplacement où seront stockés les fichiers
#             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # Utilisez le nom d'origine du fichier
#             inject_on_load: false
#             delete_on_update: true
#             delete_on_remove: true
